### ISSUE TITLE
How come the theme selected no more?

### ISSUE THREAD

**Issue by thyeun** [pojokcodeid/NvChad-v2-config#1]
@pojokcodeid Sorry for asking here, why after using your custom folder, the theme selected with SPC T H, no more functioning?

Or may i know how to get it back?

**Comment by pojokcodeid** [comment]
delete your config, and clone again from nvchad.com

**Comment by thyeun** [comment]
@pojokcodeid This is nothing to do with Nvchad, your custome modification change the key press, i have make change on that, and it now show up with ```SPC t e```

**Comment by pojokcodeid** [comment]
Ok, thanks for the clarification.
